#!/bin/bash                                                                                                                      
#To display files and folder form current directory  
for item in *                                                                                                                    
do                                                                                                                               
if [ -d $item]                                                                                                                   
then                                                                                                                             
echo $item                                                                                                                       
fi                                                                                                                               
done  
